-- Run this in your Supabase SQL Editor to add dynamic courses support

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courseId" BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  module TEXT NOT NULL,
  title TEXT NOT NULL,
  question TEXT NOT NULL,
  hint TEXT,
  "requiredElements" TEXT, -- Stored as JSON array string
  "sampleSolution" TEXT,
  "orderIndex" INTEGER DEFAULT 0
);

-- Insert a default course
INSERT INTO courses (title, description) 
VALUES ('HTML Mastery', 'Learn the foundations of HTML and web development')
ON CONFLICT DO NOTHING;
