-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  password TEXT,
  role TEXT,
  "mentorId" BIGINT DEFAULT NULL,
  "profilePic" TEXT DEFAULT '',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS progress (
  "userId" BIGINT PRIMARY KEY REFERENCES users(id),
  "currentStage" INTEGER DEFAULT 0,
  "completedStages" TEXT DEFAULT '[]',
  answers TEXT DEFAULT '{}',
  attempts TEXT DEFAULT '{}',
  "lastActiveDate" TEXT DEFAULT NULL,
  "streakCount" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" BIGINT REFERENCES users(id),
  "receiverId" BIGINT REFERENCES users(id),
  content TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentorId" BIGINT REFERENCES users(id),
  "studentId" BIGINT REFERENCES users(id),
  topic TEXT,
  date TEXT,
  link TEXT,
  attendance TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentorId" BIGINT REFERENCES users(id),
  "studentId" BIGINT REFERENCES users(id),
  title TEXT,
  description TEXT,
  "dueDate" TEXT
);

CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignmentId" BIGINT REFERENCES assignments(id),
  "studentId" BIGINT REFERENCES users(id),
  "fileData" TEXT,
  "fileName" TEXT,
  grade TEXT DEFAULT '',
  comment TEXT DEFAULT '',
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert default mentor if not exists
INSERT INTO users (name, password, role) 
VALUES ('Mentor', 'admin123', 'admin')
ON CONFLICT (name) DO NOTHING;
